Allow using relative path for config file
The example in the readme for knife-azure doesn't actually work.

knife azure image list
ERROR: Unable to find file - ~/.azure_settings.publishsettings

Expand the provided path first so we can find the file.