Properly require `winrm` gem
This fixes the following exception that is raised during bootstrap:

  NameError: uninitialized constant Chef::Knife::Winrm::WinRM